version : '3'
services:
    neodb:
        image: 'neo4j:3.5'
        environment:
            - NEO4J_AUTH=neo4j/pass123456
            - NEO4J_dbms_security_procedures_unrestricted=algo.*
        ports:
            - '7474:7474'
            - '7687:7687'
        volumes:
            - ./data/neo4j/data:/data
            - ./data/neo4j/logs:/logs
            - ./data/neo4j/import:/var/lib/neo4j/import
            - ./data/neo4j/plugins:/plugins
    pgdb:
        image: 'postgres:latest'
        environment: 
            - POSTGRES_USER=pg
            - POSTGRES_PASSWORD=pass123456
            - POSTGRES_DB=zhongwen
        ports:
            - "5432:5432"
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app:/app
        env_file: 
            - vars.env
        ports:
            - "8890:8890"
        tty: True
        depends_on:
            - neodb
            - pgdb
        command: jupyter notebook --ip 0.0.0.0 --no-browser --allow-root --port 8890